### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by alextegelid** [vontio/sublime-line-endings-unify#2]
The plugin crashes and this error is output to the console.
```
Traceback (most recent call last):
  File "LineEndingsUnify in /Users/alex/Library/Application Support/Sublime Text 3/Installed Packages/Line Endings Unify.sublime-package", line 37, in onInputExtensions
  File "LineEndingsUnify in /Users/alex/Library/Application Support/Sublime Text 3/Installed Packages/Line Endings Unify.sublime-package", line 22, in unifyLineEnding
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 470: ordinal not in range(128)
```

I'm on a MacBook Air with ST3, stable channel, build 3083.

**Comment by SeanHayes** [comment]
Same here

**Comment by vontio** [comment]
fixed ;)
